name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - KOSALSENSOK096
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🚀
        
        Please fill out the information below to help us understand your suggestion better.
        
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - New Functionality
        - Enhancement to Existing Feature
        - Performance Improvement
        - User Interface/Experience
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        I would like to see [...]
        This would help by [...]
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        Alternative 1: [...]
        Alternative 2: [...]
        
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: dropdown
    id: willing-to-help
    attributes:
      label: Are you willing to help implement this feature?
      options:
        - Yes, I can help with implementation
        - Yes, I can help with testing
        - No, I cannot help at this time
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have searched the existing feature requests and this is not a duplicate
          required: true 